spring.application.name=charter.monitoring
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/citizen_charter_system
spring.datasource.username=root
spring.datasource.password=Rane@14092005